version: '3'
services:
  access-manager:
    build:
      context: ./
      dockerfile: ./apps/access-manager/Dockerfile
    restart: always
    hostname: access-manager
    env_file:
      - .env
    networks:
      - backend
    links:
      - db

  token-manager:
    build:
      context: ./
      dockerfile: ./apps/token-manager/Dockerfile
    restart: always
    hostname: token-manager
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend
    links:
      - db

  db:
    image: 'mongo:3.7'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - './db/data/db-files:/data/db'
      - './db/init/:/docker-entrypoint-initdb.d/'
    ports:
      - 27017:27017
    networks:
      - backend
networks:
  backend:
    driver: bridge
